### ISSUE TITLE
CalendarBot HttpRequestException when find the General Luis service

### ISSUE THREAD

**Issue by capri02** [microsoft/botframework-skills#294]
#### What project is affected?
Calender Skill

#### What language is this in?
C#, .Net

#### What happens?
Getting a "System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden) exception when I run the Calendar Skill. The exception occurs in **MainDialog.cs**. 
The error occurs in both webchat and emulator.

#### What are the steps to reproduce this issue?
1. Create luis resources (authoring & prediction) in e.luis.ai.
2. Setup the Calendar skill

#### What were you expecting to happen?

I was expecting to receive a login option and meetings rooms response.

#### Can you share any logs, error output, etc.?
**MainDialog.cs**

**Function: OnContinueDialogAsync**

```javascript
localizedServices.LuisServices.TryGetValue("General", out var generalLuisService);
                if (generalLuisService != null)
                {
                    var generalResult = await generalLuisService.RecognizeAsync<General>(innerDc.Context, cancellationToken);
                    innerDc.Context.TurnState[StateProperties.GeneralLuisResultKey] = generalResult;
                }
```

> "System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
 at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
 at Microsoft.Bot.Builder.AI.Luis.LuisRecognizerOptionsV3.RecognizeAsync(ITurnContext turnContext, String utterance, LuisPredictionOptions options, HttpClient httpClient, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.AI.Luis.LuisRecognizerOptionsV3.RecognizeInternalAsync(ITurnContext turnContext, HttpClient httpClient, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.AI.Luis.LuisRecognizer.RecognizeInternalAsync(ITurnContext turnContext, LuisRecognizerOptions predictionOptions, Dictionary`2 telemetryProperties, Dictionary`2 telemetryMetrics, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.AI.Luis.LuisRecognizer.RecognizeAsync[T](ITurnContext turnContext, CancellationToken cancellationToken)
 at CalendarSkill.Dialogs.MainDialog.OnContinueDialogAsync(DialogContext innerDc, CancellationToken cancellationToken) in C:\Users\NANAI\source\repos\botframework-skills\skills\csharp\calendarskill\Dialogs\MainDialog.cs:line 169
 at Microsoft.Bot.Builder.Dialogs.ComponentDialog.ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogExtensions.RunAsync(Dialog dialog, ITurnContext turnContext, IStatePropertyAccessor`1 accessor, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.ActivityHandler.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
 at CalendarSkill.Bots.DefaultActivityHandler`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in C:\Users\NANAI\source\repos\botframework-skills\skills\csharp\calendarskill\Bots\DefaultActivityHandler.cs:line 36
 at Microsoft.Bot.Solutions.Middleware.EventDebuggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Solutions.Middleware.SetLocaleMiddleware.OnTurnAsync(ITurnContext context, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.ShowTypingMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.TranscriptLoggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.TelemetryInitializerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)"
valueType: "https://www.botframework.com/schemas/error"

#### Any screenshots or additional context?
My general guess is that the error relates to luis resources in EU region. Seems like the **LuisRecognizer** class in namespace **Microsoft.Bot.Builder.AI.Luis** refers to US region luis only.

![screenshot3](https://user-images.githubusercontent.com/6074308/90265042-4ab0b280-de52-11ea-9461-4c99e472cd85.png)
![screenshot2](https://user-images.githubusercontent.com/6074308/90265045-4b494900-de52-11ea-967e-69fbb915765d.png)
![screenshot1](https://user-images.githubusercontent.com/6074308/90265047-4be1df80-de52-11ea-974e-02d5018547a9.png)

**Comment by peterinnesmsft** [comment]
@KayMKM can you provide an update on the status of this?

**Comment by capri02** [comment]
Here are the cognitive model settings for general and calendar intents:

```javascript
{
  "defaultLocale": "en-us",
  "cognitiveModels": {
    "en-us": {
      "languageModels": [
        {
          "version": "0.1",
          "authoringkey": "xxxxxxx",
          "id": "Calendar",
          "appid": "xxxxxxxxx",
          "region": "westeurope",
          "endpoint": "https://calendarbot-luisauthoring-xxxxxx.cognitiveservices.azure.com/",
          "subscriptionkey": "xxxxxxx",
          "name": "CalendarBoten-us_Calendar"
        },
        {
          "version": "0.1",
          "authoringkey": "xxxxxxxx",
          "id": "General",
          "appid": "XXXXXXXXX",
          "region": "westeurope",
          "endpoint": "https://calendarbot-luisauthoring-xxxxx.cognitiveservices.azure.com/",
          "subscriptionkey": "XXXXX",
          "name": "CalendarBoten-us_General"
        }
      ]
    }
  }
}
```

Please let me know if you need more information.

**Comment by KayMKM** [comment]
here is my settings:
```
{
  "cognitiveModels": {
    "en-us": {
      "languageModels": [
        {
          "name": "calendar",
          "version": "0.1",
          "region": "westeurope",
          "subscriptionKey": "xxx",
          "appId": "xxx",
          "id": "Calendar",
          "authoringRegion": "westeurope",
          "authoringKey": "xxx"
        },
        {
          "name": "yuesuCalendarSkill0911enen_General",
          "version": "0.1",
          "region": "westeurope",
          "subscriptionKey": "xxx",
          "appId": "xxx",
          "id": "General",
          "authoringRegion": "westeurope",
          "authoringKey": "xxx"
        }
      ]
    }
  },
  "defaultLocale": "en-us"
}
```
I am not sure will the endpoint occur error. You can try to remove it and try again.

**Comment by lauren-mills** [comment]
@capri02 - This error 403 (Forbidden) can also be a sign that your subscription key has run out of quota. Do you have the same value in the authoringKey and subscriptionKey properties by chance?

**Comment by capri02** [comment]
Apologies for late response @KayMKM . But removing the endpoints from the cognitive settings did not help. I got the same 403 forbidden access error for LUIS.

 @lauren-mills: I checked the quota and it looked fine as well. And, no, the authoringKey and subscriptionKey  properties have different values.

**Comment by KayMKM** [comment]
@capri02 Could you try this endpoint in your luis portal to confirm you can access the luis resource?
![image](https://user-images.githubusercontent.com/19773357/91944029-0a956f00-ed30-11ea-86bc-8ed873dbe1b1.png)

**Comment by capri02** [comment]
My sincere apologies for such a delayed response. It seems like the prediction resource was missing in the luis portal. After I created that the calendar bot worked and responded back with the meeting data.

I am closing this issue since it is resolved and working after creating the prediction resource.
